0-run

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,10 @@
 #!/bin/bash
 python3 "$PYFILE"
+if [ -z "$PYFILE" ]; then
+  echo "Error: The PYFILE environment variable is not set."
+  exit 1
+fi
+if [ ! -f "$PYFILE" ]; then
+	echo "Error: The Python file '$PYFILE' does not exist."
+	exit 1
+fi
